<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>94866f7e-51ed-4001-a3fd-5ad34ed927fe</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sms.Application\Sms.Application.csproj" />
    <ProjectReference Include="..\Sms.Infrastructure\Sms.Infrastructure.csproj" />
    <ProjectReference Include="..\Sms.Shared.Kernel\Sms.Shared.Kernel.csproj" />
    <ProjectReference Include="..\Sms.Modules.Identity\Sms.Modules.Identity.csproj" />
    <ProjectReference Include="..\Sms.Modules.Tenancy\Sms.Modules.Tenancy.csproj" />
    <ProjectReference Include="..\Sms.Modules.Sis\Sms.Modules.Sis.csproj" />
    <ProjectReference Include="..\Sms.Modules.Staffing\Sms.Modules.Staffing.csproj" />
    <ProjectReference Include="..\Sms.Modules.Academics\Sms.Modules.Academics.csproj" />
    <ProjectReference Include="..\Sms.Modules.Attendance\Sms.Modules.Attendance.csproj" />
    <ProjectReference Include="..\Sms.Modules.Finance\Sms.Modules.Finance.csproj" />
    <ProjectReference Include="..\Sms.Modules.Hostel\Sms.Modules.Hostel.csproj" />
    <ProjectReference Include="..\Sms.Modules.Sports\Sms.Modules.Sports.csproj" />
    <ProjectReference Include="..\Sms.Modules.Transport\Sms.Modules.Transport.csproj" />
    <ProjectReference Include="..\Sms.Modules.Comms\Sms.Modules.Comms.csproj" />
    <ProjectReference Include="..\Sms.Modules.Reporting\Sms.Modules.Reporting.csproj" />
    <ProjectReference Include="..\Sms.Modules.AiSearch\Sms.Modules.AiSearch.csproj" />
    <ProjectReference Include="..\Sms.Modules.Tasks\Sms.Modules.Tasks.csproj" />
    <ProjectReference Include="..\Sms.Modules.VehicleChecks\Sms.Modules.VehicleChecks.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
    <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.16.0" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.16.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.15.2" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.1" />
  </ItemGroup>

</Project>
