-- Auto-generated from live SQL Server metadata (read-only extraction). One CREATE TABLE per source table.
-- Types mapped per docs audit section D. Defaults translated where mechanically safe; SQL-Server-specific
-- defaults with no safe mechanical translation are flagged inline with /* REVIEW */.

CREATE TABLE "dbo"."_Migration_UnmatchedDirectoryRows" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "SourceTable" varchar(20) NOT NULL,
    "SourceId" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "Reason" varchar(20) NOT NULL,
    "MatchCount" integer NOT NULL,
    "CreatedAt" timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE "dbo"."AcademicPeriodSchedules" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "DraftJson" text,
    "PublishedJson" text,
    "DraftSavedAt" timestamptz,
    "PublishedAt" timestamptz
);

CREATE TABLE "dbo"."AcademicSessions" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "Name" varchar(40) NOT NULL,
    "StartsOn" date,
    "EndsOn" date,
    "IsCurrent" boolean DEFAULT false NOT NULL,
    "CreatedAt" timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE "dbo"."Achievements" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "StudentId" uuid NOT NULL,
    "Title" varchar(200) NOT NULL,
    "AwardedOn" date NOT NULL,
    "Icon" varchar(20) DEFAULT 'award' NOT NULL,
    "Hue" varchar(20) DEFAULT 'yellow' NOT NULL,
    "CreatedAt" timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE "dbo"."Address" (
    "AddressId" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    "StudentId" integer,
    "CurrentAddress" varchar(500),
    "PermanentAddress" varchar(500)
);

CREATE TABLE "dbo"."AiSearchConversation" (
    "ConversationId" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "ResolvedEntityId" uuid,
    "ResolvedEntityType" varchar(20),
    "LanguageOverride" varchar(10),
    "PendingCandidates" text,
    "LastIntent" varchar(60),
    "CreatedAt" timestamptz NOT NULL,
    "ExpiresAt" timestamptz NOT NULL
);

CREATE TABLE "dbo"."AiSearchLog" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Role" varchar(100) NOT NULL,
    "Question" varchar(300) NOT NULL,
    "DetectedLanguage" varchar(20),
    "DetectedIntent" varchar(60),
    "ResultCount" integer DEFAULT 0 NOT NULL,
    "Success" boolean NOT NULL,
    "At" timestamptz NOT NULL
);

CREATE TABLE "dbo"."Announcements" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "Title" varchar(200) NOT NULL,
    "Body" varchar(2000),
    "Date" timestamptz DEFAULT now() NOT NULL,
    "From" varchar(120),
    "Role" varchar(40),
    "Type" varchar(20) DEFAULT 'info' NOT NULL,
    "Pinned" boolean DEFAULT false NOT NULL,
    "Audience" varchar(20),
    "CreatorUserId" uuid,
    "RecipientsJson" text,
    "AttachmentFileName" varchar(260),
    "AttachmentContentType" varchar(120)
);

CREATE TABLE "dbo"."Assignments" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "Title" varchar(200) NOT NULL,
    "ClassId" uuid,
    "ClassName" varchar(80),
    "Subject" varchar(80),
    "DueDate" date,
    "Description" text,
    "ImageUri" text,
    "Status" varchar(20) DEFAULT 'active' NOT NULL,
    "Period" integer
);

CREATE TABLE "dbo"."AttendanceAlertConfigs" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "NoticeDays" integer DEFAULT 3 NOT NULL,
    "EmailDays" integer DEFAULT 5 NOT NULL,
    "AutoSend" boolean DEFAULT false NOT NULL,
    "AutoTime" varchar(5) DEFAULT '09:00' NOT NULL,
    "AutoChannel" varchar(10) DEFAULT 'app' NOT NULL,
    "LastAutoSentDate" date,
    "UpdatedAt" timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE "dbo"."AttendanceRecords" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "ClassId" uuid NOT NULL,
    "StudentId" uuid NOT NULL,
    "Date" date NOT NULL,
    "Status" varchar(20) NOT NULL,
    "MarkedBy" uuid
);

CREATE TABLE "dbo"."AuditLog" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid,
    "ActorId" uuid,
    "Action" varchar(128) NOT NULL,
    "Target" varchar(256),
    "Kind" varchar(64),
    "At" timestamptz DEFAULT now() NOT NULL,
    "ActorName" varchar(200),
    "Role" varchar(40)
);

CREATE TABLE "dbo"."AuditLogs" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "ActorUserId" uuid,
    "Action" varchar(100) NOT NULL,
    "Module" varchar(50) NOT NULL,
    "EntityType" varchar(100) NOT NULL,
    "EntityId" varchar(100) NOT NULL,
    "TimestampUtc" timestamptz DEFAULT now() NOT NULL,
    "BeforeData" text,
    "AfterData" text
);

CREATE TABLE "dbo"."BankDetail" (
    "BankId" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    "StudentId" integer,
    "BankName" varchar(100),
    "Branch" varchar(100),
    "IFSC" varchar(50)
);

CREATE TABLE "dbo"."Boardings" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "TripId" uuid NOT NULL,
    "StudentId" uuid NOT NULL,
    "StopId" uuid,
    "State" varchar(10) DEFAULT 'pending' NOT NULL,
    "At" timestamptz NOT NULL
);

-- ResultJson is nullable (per live SQL Server: is_nullable=1) -- a NULL row is the
-- "claimed but not yet completed" placeholder BulkImportRepository.TryClaimBatchAsync inserts
-- before processing; the mechanical table-conversion pass had wrongly tightened this to NOT NULL.
CREATE TABLE "dbo"."BulkImportBatches" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "ImportId" uuid NOT NULL,
    "BatchIndex" integer NOT NULL,
    "ResultJson" text,
    "CreatedAt" timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE "dbo"."BusAssignments" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "TeacherUserId" uuid NOT NULL,
    "BusId" uuid NOT NULL
);

CREATE TABLE "dbo"."BusDriverAssignments" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "BusId" uuid NOT NULL,
    "StaffId" uuid NOT NULL,
    "Role" varchar(10) NOT NULL,
    "AssignedAt" timestamptz DEFAULT now() NOT NULL,
    "UnassignedAt" timestamptz,
    "AssignedByUserId" uuid
);

CREATE TABLE "dbo"."Buses" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "BusNo" varchar(40) NOT NULL,
    "RouteName" varchar(80),
    "Driver" varchar(120),
    "DriverPhone" varchar(32),
    "RouteId" uuid,
    "DriverStaffId" uuid,
    "ConductorStaffId" uuid,
    "Capacity" integer
);

CREATE TABLE "dbo"."BusParentAlerts" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "TripId" uuid NOT NULL,
    "StudentId" uuid NOT NULL,
    "ParentUserId" uuid NOT NULL,
    "Kind" varchar(40) NOT NULL,
    "CreatedAt" timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE "dbo"."BusStops" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "BusId" uuid NOT NULL,
    "Name" varchar(120) NOT NULL,
    "Time" varchar(10),
    "Seq" integer NOT NULL,
    "Lat" double precision DEFAULT 0 NOT NULL,
    "Lng" double precision DEFAULT 0 NOT NULL
);

CREATE TABLE "dbo"."BusTravelingTeachers" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "BusId" uuid NOT NULL,
    "TeacherUserId" uuid NOT NULL
);

CREATE TABLE "dbo"."CalendarEvents" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "Title" varchar(200) NOT NULL,
    "Date" date NOT NULL,
    "Time" varchar(10),
    "Type" varchar(20) NOT NULL,
    "Description" text,
    "ChannelsJson" varchar(200)
);

CREATE TABLE "dbo"."ChatMessages" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "ThreadId" uuid NOT NULL,
    "SenderId" uuid,
    "Text" varchar(2000) NOT NULL,
    "SentAt" timestamptz NOT NULL,
    "ImageUrl" text,
    "CorrelationId" uuid DEFAULT gen_random_uuid() NOT NULL,
    "DeliveredAt" timestamptz,
    "ReadAt" timestamptz
);

CREATE TABLE "dbo"."ChatThreads" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "Name" varchar(120) NOT NULL,
    "Role" varchar(40),
    "LastMessage" varchar(400),
    "LastAt" timestamptz,
    "Unread" integer DEFAULT 0 NOT NULL,
    "IsGroup" boolean DEFAULT false NOT NULL,
    "ChildId" uuid,
    "OwnerUserId" uuid,
    "ContactUserId" uuid
);

CREATE TABLE "dbo"."CheckIns" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Kind" varchar(3) NOT NULL,
    "At" timestamptz NOT NULL,
    "Lat" double precision DEFAULT 0 NOT NULL,
    "Lng" double precision DEFAULT 0 NOT NULL,
    "AccuracyMeters" double precision DEFAULT 0 NOT NULL,
    "DistanceMeters" double precision DEFAULT 0 NOT NULL,
    "Verified" boolean DEFAULT false NOT NULL
);

CREATE TABLE "dbo"."Classes" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "Name" varchar(80) NOT NULL,
    "Grade" varchar(20),
    "Section" varchar(20),
    "Subject" varchar(80),
    "Room" varchar(40),
    "StudentCount" integer DEFAULT 0 NOT NULL,
    "ClassTeacherId" uuid,
    "AcademicSessionId" uuid
);

CREATE TABLE "dbo"."ClassSubjects" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "ClassId" uuid NOT NULL,
    "SubjectId" uuid,
    "Name" varchar(80) NOT NULL
);

CREATE TABLE "dbo"."ClassTestSchedules" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "DraftJson" text,
    "PublishedJson" text,
    "DraftSavedAt" timestamptz,
    "PublishedAt" timestamptz
);

CREATE TABLE "dbo"."Complaints" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "Subject" varchar(200) NOT NULL,
    "From" varchar(120),
    "Category" varchar(40),
    "Priority" varchar(10) DEFAULT 'medium' NOT NULL,
    "Status" varchar(20) DEFAULT 'open' NOT NULL,
    "Age" varchar(20),
    "Assignee" varchar(120),
    "Body" varchar(2000),
    "CreatedByUserId" uuid
);

CREATE TABLE "dbo"."Driver" (
    "DriverId" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    "OrganizationId" integer,
    "SchoolId" integer,
    "DriverName" varchar(100),
    "Phone" varchar(20),
    "LicenseNumber" varchar(50),
    "Address" varchar(500),
    "CreatedDate" timestamptz DEFAULT now(),
    "IsActive" boolean DEFAULT true
);

CREATE TABLE "dbo"."ExamAttendanceRecords" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "ExamPaperId" uuid NOT NULL,
    "StudentId" uuid NOT NULL,
    "Status" varchar(20) NOT NULL,
    "MarkedBy" uuid
);

CREATE TABLE "dbo"."ExamClasses" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "ExamId" uuid NOT NULL,
    "ClassId" uuid NOT NULL
);

CREATE TABLE "dbo"."ExamPapers" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "ExamId" uuid,
    "ClassId" uuid,
    "Name" varchar(120),
    "Subject" varchar(80),
    "SubjectId" uuid,
    "Date" date,
    "StartTime" varchar(10),
    "DurationMin" integer,
    "MaxMarks" integer DEFAULT 100 NOT NULL,
    "Room" varchar(40),
    "Invigilator1" varchar(120),
    "Invigilator2" varchar(120),
    "Status" varchar(20) DEFAULT 'upcoming' NOT NULL,
    "Topics" text
);

CREATE TABLE "dbo"."Exams" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "Name" varchar(120) NOT NULL,
    "Type" varchar(40),
    "Grades" varchar(40),
    "FromDate" date,
    "ToDate" date,
    "SubjectCount" integer DEFAULT 0 NOT NULL,
    "Status" varchar(20) DEFAULT 'draft' NOT NULL,
    "MarksEnteredPct" numeric(5,2) DEFAULT 0 NOT NULL,
    "Published" boolean DEFAULT false NOT NULL,
    "AcademicSessionId" uuid
);

CREATE TABLE "dbo"."FeeHeads" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "Name" varchar(120) NOT NULL,
    "Code" varchar(40),
    "Active" boolean DEFAULT true NOT NULL,
    "IsSystem" boolean DEFAULT false NOT NULL,
    "IsTransportFeeHead" boolean DEFAULT false NOT NULL,
    "Description" text
);

CREATE TABLE "dbo"."FeeInvoiceLines" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "InvoiceId" uuid NOT NULL,
    "FeeHeadId" uuid,
    "FeeHeadName" varchar(120) NOT NULL,
    "Amount" numeric(18,2) DEFAULT 0 NOT NULL,
    "CreatedAt" timestamptz DEFAULT now() NOT NULL,
    "FeeHeadDescription" text
);

CREATE TABLE "dbo"."FeeInvoices" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "StudentId" uuid NOT NULL,
    "Period" varchar(60),
    "DueDate" date,
    "Amount" numeric(18,2) DEFAULT 0 NOT NULL,
    "Status" varchar(10) DEFAULT 'due' NOT NULL,
    "PaidOn" date,
    "Method" varchar(40),
    "PaidAmount" numeric(18,2) DEFAULT 0 NOT NULL
);

CREATE TABLE "dbo"."FeePaymentOrders" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "InvoiceId" uuid NOT NULL,
    "RazorpayOrderId" varchar(100) NOT NULL,
    "AmountPaise" bigint NOT NULL,
    "Status" varchar(20) DEFAULT 'Created' NOT NULL,
    "InitiatedBy" varchar(20) NOT NULL,
    "CreatedAt" timestamptz DEFAULT now() NOT NULL,
    "UpdatedAt" timestamptz
);

CREATE TABLE "dbo"."FeePayments" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "StudentId" uuid NOT NULL,
    "StudentName" varchar(200),
    "ClassLabel" varchar(40),
    "FeeType" varchar(20) DEFAULT 'academic' NOT NULL,
    "Amount" numeric(18,2) DEFAULT 0 NOT NULL,
    "Method" varchar(40),
    "Ref" varchar(80),
    "Date" date DEFAULT now() NOT NULL,
    "InvoiceId" uuid,
    "HeadId" varchar(64),
    "CreatedAt" timestamptz DEFAULT now() NOT NULL,
    "UpdatedAt" timestamptz,
    "IdempotencyKey" uuid
);

CREATE TABLE "dbo"."FeeStructures" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "Name" varchar(200) NOT NULL,
    "AcademicYear" varchar(20) NOT NULL,
    "ClassGrade" varchar(40),
    "Section" varchar(20),
    "Currency" varchar(10) DEFAULT 'INR' NOT NULL,
    "EffectiveFrom" date NOT NULL,
    "EffectiveTo" date,
    "Status" varchar(20) DEFAULT 'active' NOT NULL,
    "Description" text,
    "AmountsJson" text DEFAULT '{}' NOT NULL,
    "AcademicSessionId" uuid,
    "CreatedAt" timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE "dbo"."FuelLogs" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "BusId" uuid NOT NULL,
    "RecordedByUserId" uuid NOT NULL,
    "OdometerKm" integer NOT NULL,
    "FuelAddedLiters" numeric(10,2) NOT NULL,
    "RecordedAt" timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE "dbo"."Grades" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "StudentId" uuid NOT NULL,
    "StudentName" varchar(200),
    "ExamPaperId" uuid NOT NULL,
    "Marks" numeric(6,2) DEFAULT 0 NOT NULL,
    "MaxMarks" numeric(6,2) DEFAULT 100 NOT NULL,
    "Grade" varchar(4),
    "Gpa" numeric(4,2) DEFAULT 0 NOT NULL,
    "Pass" boolean DEFAULT false NOT NULL,
    "Date" date
);

CREATE TABLE "dbo"."Guardian" (
    "GuardianId" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    "StudentId" integer,
    "GuardianType" varchar(50),
    "GuardianName" varchar(100),
    "Relation" varchar(50),
    "Phone" varchar(20),
    "Email" varchar(100),
    "Occupation" varchar(100),
    "Address" varchar(500),
    "Photo" varchar(500)
);

CREATE TABLE "dbo"."Homework" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "StudentId" uuid NOT NULL,
    "AssignmentId" uuid,
    "Title" varchar(200) NOT NULL,
    "SubjectId" uuid,
    "DueDate" date,
    "DueTime" varchar(10),
    "Status" varchar(20) DEFAULT 'todo' NOT NULL,
    "Priority" varchar(10) DEFAULT 'med' NOT NULL,
    "Grade" varchar(4),
    "AcademicSessionId" uuid
);

CREATE TABLE "dbo"."HostelBlocks" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "Name" varchar(80) NOT NULL,
    "Warden" varchar(120)
);

CREATE TABLE "dbo"."HostelResidents" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "RoomId" uuid NOT NULL,
    "StudentName" varchar(120) NOT NULL,
    "StudentId" uuid
);

CREATE TABLE "dbo"."HostelRooms" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "BlockId" uuid NOT NULL,
    "RoomNo" varchar(40) NOT NULL,
    "Capacity" integer DEFAULT 1 NOT NULL
);

CREATE TABLE "dbo"."Invitations" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Email" varchar(256),
    "Phone" varchar(32),
    "RoleLabel" varchar(64) NOT NULL,
    "InvitedByUserId" uuid,
    "InvitedAt" timestamptz DEFAULT now() NOT NULL,
    "ExpiresAt" timestamptz NOT NULL,
    "AcceptedAt" timestamptz,
    "RevokedAt" timestamptz,
    "LastResentAt" timestamptz
);

CREATE TABLE "dbo"."Invoices" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "TenantName" varchar(200),
    "PlanName" varchar(100),
    "Amount" numeric(18,2) DEFAULT 0 NOT NULL,
    "Status" varchar(20) DEFAULT 'open' NOT NULL,
    "Issued" timestamptz DEFAULT now() NOT NULL,
    "Due" timestamptz DEFAULT now() NOT NULL,
    "PaidOn" timestamptz,
    "CreatedAt" timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE "dbo"."IssueNotes" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "IssueId" uuid NOT NULL,
    "AuthorUserId" uuid NOT NULL,
    "Note" varchar(1000) NOT NULL,
    "CreatedAt" timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE "dbo"."Issues" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "ReporterUserId" uuid NOT NULL,
    "Category" varchar(20) NOT NULL,
    "Title" varchar(200) NOT NULL,
    "Description" varchar(2000) NOT NULL,
    "Priority" varchar(20) DEFAULT 'normal' NOT NULL,
    "Status" varchar(20) DEFAULT 'open' NOT NULL,
    "VehicleId" uuid,
    "RouteId" uuid,
    "TripId" uuid,
    "PhotoUrl" text,
    "CreatedAt" timestamptz DEFAULT now() NOT NULL,
    "UpdatedAt" timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE "dbo"."LeaveEntitlements" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "RequesterId" uuid NOT NULL,
    "Type" varchar(20) NOT NULL,
    "Year" integer NOT NULL,
    "TotalDays" integer NOT NULL
);

CREATE TABLE "dbo"."LeaveRequests" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "RequesterId" uuid,
    "ChildId" uuid,
    "Type" varchar(20) DEFAULT 'casual' NOT NULL,
    "FromDate" date,
    "ToDate" date,
    "Reason" varchar(500),
    "Substitute" varchar(120),
    "Status" varchar(20) DEFAULT 'pending' NOT NULL,
    "AppliedOn" date,
    "DecidedBy" uuid,
    "DecidedNote" varchar(500),
    "Priority" varchar(10) DEFAULT 'medium' NOT NULL,
    "AttachmentUrls" text,
    "Note" varchar(1000)
);

CREATE TABLE "dbo"."LibraryBooks" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "Title" varchar(200) NOT NULL,
    "Author" varchar(120) NOT NULL,
    "Subject" varchar(80),
    "IssuedTo" varchar(120),
    "DueDate" date,
    "Status" varchar(20) DEFAULT 'available' NOT NULL
);

CREATE TABLE "dbo"."MedicalInfo" (
    "MedicalId" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    "StudentId" integer,
    "MedicalCondition" varchar(50),
    "Allergies" varchar(200),
    "Medications" varchar(200),
    "MedicalHistory" varchar(500)
);

CREATE TABLE "dbo"."Notifications" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "Icon" varchar(40),
    "Tone" varchar(20),
    "Title" varchar(200) NOT NULL,
    "Body" varchar(1000),
    "Time" varchar(40),
    "Unread" boolean DEFAULT true NOT NULL,
    "UserId" uuid
);

CREATE TABLE "dbo"."OnboardingChecklist" (
    "OnboardingId" uuid NOT NULL,
    "Seq" integer NOT NULL,
    "Label" varchar(100) NOT NULL,
    "Done" boolean DEFAULT false NOT NULL
);

CREATE TABLE "dbo"."OnboardingItems" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid,
    "Name" varchar(200) NOT NULL,
    "Slug" varchar(100) NOT NULL,
    "Owner" varchar(120),
    "Value" numeric(18,2) DEFAULT 0 NOT NULL,
    "Stage" varchar(20) DEFAULT 'lead' NOT NULL,
    "Age" integer DEFAULT 0 NOT NULL,
    "ContactName" varchar(200),
    "ContactEmail" varchar(256),
    "ContactPhone" varchar(40),
    "Address" varchar(300)
);

CREATE TABLE "dbo"."Organization" (
    "OrganizationId" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    "Name" varchar(200) NOT NULL,
    "Email" varchar(100),
    "Phone" varchar(20),
    "Username" varchar(100) NOT NULL,
    "PasswordHash" varchar(500) NOT NULL,
    "CreatedBy" integer,
    "CreatedDate" timestamptz DEFAULT now(),
    "UpdatedBy" integer,
    "UpdatedDate" timestamptz,
    "IsActive" boolean DEFAULT true,
    "IsDeleted" boolean DEFAULT false
);

CREATE TABLE "dbo"."Organizations" (
    "OrganizationId" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    "Name" varchar(200) NOT NULL,
    "Email" varchar(100),
    "Phone" varchar(20),
    "Username" varchar(100) NOT NULL,
    "PasswordHash" varchar(500) NOT NULL,
    "CreatedBy" integer,
    "CreatedDate" timestamptz DEFAULT now(),
    "UpdatedBy" integer,
    "UpdatedDate" timestamptz,
    "IsActive" boolean DEFAULT true,
    "IsDeleted" boolean DEFAULT false
);

CREATE TABLE "dbo"."OtpCodes" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "Phone" varchar(32),
    "CodeHash" varchar(128) NOT NULL,
    "ExpiresAt" timestamptz NOT NULL,
    "ConsumedAt" timestamptz,
    "CreatedAt" timestamptz DEFAULT now() NOT NULL,
    "Identifier" varchar(256),
    "Channel" varchar(10)
);

CREATE TABLE "dbo"."Parent" (
    "ParentId" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    "StudentId" integer,
    "FatherName" varchar(100),
    "FatherEmail" varchar(100),
    "FatherPhone" varchar(20),
    "FatherOccupation" varchar(100),
    "FatherPhoto" varchar(500),
    "MotherName" varchar(100),
    "MotherEmail" varchar(100),
    "MotherPhone" varchar(20),
    "MotherOccupation" varchar(100),
    "MotherPhoto" varchar(500)
);

CREATE TABLE "dbo"."ParentStudentLinks" (
    "ParentUserId" uuid NOT NULL,
    "StudentId" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "CreatedAt" timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE "dbo"."PayrollRunLines" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "RunId" uuid NOT NULL,
    "PersonType" varchar(10) NOT NULL,
    "PersonId" uuid NOT NULL,
    "Name" varchar(200) NOT NULL,
    "Role" varchar(120),
    "Dept" varchar(120),
    "Gross" numeric(18,2) DEFAULT 0 NOT NULL,
    "Deductions" numeric(18,2) DEFAULT 0 NOT NULL,
    "Net" numeric(18,2) DEFAULT 0 NOT NULL,
    "Basic" numeric(18,2) DEFAULT 0 NOT NULL,
    "Hra" numeric(18,2) DEFAULT 0 NOT NULL,
    "Allowances" numeric(18,2) DEFAULT 0 NOT NULL,
    "Epf" numeric(18,2) DEFAULT 0 NOT NULL,
    "ProfTax" numeric(18,2) DEFAULT 0 NOT NULL,
    "OtherDeductions" numeric(18,2) DEFAULT 0 NOT NULL
);

CREATE TABLE "dbo"."PayrollRuns" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "Period" varchar(7) NOT NULL,
    "Year" integer DEFAULT 0 NOT NULL,
    "Month" varchar(20),
    "Status" varchar(20) DEFAULT 'run' NOT NULL,
    "StaffCount" integer DEFAULT 0 NOT NULL,
    "Gross" numeric(18,2) DEFAULT 0 NOT NULL,
    "Deductions" numeric(18,2) DEFAULT 0 NOT NULL,
    "Net" numeric(18,2) DEFAULT 0 NOT NULL,
    "RunBy" uuid,
    "RunAt" timestamptz,
    "ApprovedBy" uuid,
    "ApprovedAt" timestamptz,
    "CreatedAt" timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE "dbo"."Payslips" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Month" varchar(20),
    "Year" integer DEFAULT 0 NOT NULL,
    "Gross" numeric(18,2) DEFAULT 0 NOT NULL,
    "Deductions" numeric(18,2) DEFAULT 0 NOT NULL,
    "Net" numeric(18,2) DEFAULT 0 NOT NULL,
    "Status" varchar(20) DEFAULT 'pending' NOT NULL,
    "Basic" numeric(18,2) DEFAULT 0 NOT NULL,
    "Hra" numeric(18,2) DEFAULT 0 NOT NULL,
    "Allowances" numeric(18,2) DEFAULT 0 NOT NULL,
    "Epf" numeric(18,2) DEFAULT 0 NOT NULL,
    "ProfTax" numeric(18,2) DEFAULT 0 NOT NULL,
    "OtherDeductions" numeric(18,2) DEFAULT 0 NOT NULL
);

CREATE TABLE "dbo"."PeriodAttendanceAudit" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "RecordId" uuid NOT NULL,
    "ClassId" uuid NOT NULL,
    "StudentId" uuid NOT NULL,
    "Date" date NOT NULL,
    "Period" integer NOT NULL,
    "Subject" varchar(120) NOT NULL,
    "FromStatus" varchar(20),
    "ToStatus" varchar(20) NOT NULL,
    "ActorId" uuid,
    "ActorName" varchar(200),
    "ActorRole" varchar(64),
    "At" timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE "dbo"."PeriodAttendanceRecords" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "ClassId" uuid NOT NULL,
    "StudentId" uuid NOT NULL,
    "Date" date NOT NULL,
    "Period" integer NOT NULL,
    "PeriodId" uuid,
    "Subject" varchar(120) NOT NULL,
    "SubjectId" uuid,
    "Status" varchar(20) NOT NULL,
    "MarkedBy" uuid,
    "MarkedByRole" varchar(64),
    "CreatedAt" timestamptz DEFAULT now() NOT NULL,
    "UpdatedAt" timestamptz DEFAULT now() NOT NULL,
    "GeoFenceStatus" varchar(32),
    "GeoDistanceMeters" integer,
    "GeoCapturedAt" timestamptz,
    "UpdatedBy" uuid,
    "UpdatedByRole" varchar(64)
);

CREATE TABLE "dbo"."PersonExtras" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "PersonType" varchar(20) NOT NULL,
    "PersonId" uuid NOT NULL,
    "ExtrasJson" text DEFAULT '{}' NOT NULL,
    "UpdatedAt" timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE "dbo"."Plans" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "Name" varchar(100) NOT NULL,
    "Tier" varchar(20) NOT NULL,
    "Pricing" varchar(20) DEFAULT 'flat' NOT NULL,
    "Price" numeric(18,2) DEFAULT 0 NOT NULL,
    "PerStudent" numeric(18,2),
    "MinStudents" integer,
    "Period" varchar(20) DEFAULT 'month' NOT NULL,
    "FeaturesCsv" varchar(4000),
    "LimitsStudents" integer DEFAULT 0 NOT NULL,
    "LimitsStaff" integer DEFAULT 0 NOT NULL,
    "LimitsStorageGb" integer DEFAULT 0 NOT NULL,
    "Visibility" varchar(20) DEFAULT 'draft' NOT NULL,
    "Audience" varchar(20) DEFAULT 'all' NOT NULL,
    "Band" varchar(100),
    "OfferLabel" varchar(100),
    "OfferPct" integer,
    "Color" varchar(40),
    "Description" varchar(1000)
);

CREATE TABLE "dbo"."PlanUpgradeRequests" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "FromPlanId" uuid,
    "ToPlanId" uuid NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "Currency" varchar(8) DEFAULT 'INR' NOT NULL,
    "Mode" varchar(20) NOT NULL,
    "Status" varchar(40) NOT NULL,
    "InvoiceId" uuid,
    "RazorpayOrderId" varchar(80),
    "RazorpayPaymentId" varchar(80),
    "RequestedByUserId" uuid,
    "ReviewedByUserId" uuid,
    "Notes" varchar(500),
    "CreatedAt" timestamptz DEFAULT now() NOT NULL,
    "UpdatedAt" timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE "dbo"."PlatformMetricsSnapshot" (
    "Month" date NOT NULL,
    "Mrr" numeric(18,2) DEFAULT 0 NOT NULL,
    "ActiveClients" integer DEFAULT 0 NOT NULL,
    "CancelledClients" integer DEFAULT 0 NOT NULL,
    "CreatedAt" timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE "dbo"."PreviousSchool" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    "StudentId" integer,
    "SchoolName" varchar(200),
    "Address" varchar(500)
);

CREATE TABLE "dbo"."RefreshTokens" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "UserId" uuid NOT NULL,
    "TokenHash" varchar(128) NOT NULL,
    "ExpiresAt" timestamptz NOT NULL,
    "RevokedAt" timestamptz,
    "CreatedAt" timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE "dbo"."RoleTemplateOverrides" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "Role" varchar(32) NOT NULL,
    "Module" varchar(64) NOT NULL,
    "Cap" varchar(1) NOT NULL,
    "Effect" varchar(8) NOT NULL,
    "UpdatedAt" timestamptz DEFAULT now() NOT NULL,
    "UpdatedByUserId" uuid
);

CREATE TABLE "dbo"."Route" (
    "RouteId" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    "OrganizationId" integer,
    "SchoolId" integer,
    "RouteName" varchar(100)
);

CREATE TABLE "dbo"."RouteGeometries" (
    "RouteId" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "StopSequenceHash" varchar(64) NOT NULL,
    "Format" varchar(32) NOT NULL,
    "EncodedPolyline" text NOT NULL,
    "DistanceMeters" integer NOT NULL,
    "DurationSeconds" integer NOT NULL,
    "Provider" varchar(32) NOT NULL,
    "GeneratedAt" timestamptz NOT NULL
);

CREATE TABLE "dbo"."RouteStops" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "RouteId" uuid NOT NULL,
    "Name" varchar(120) NOT NULL,
    "Seq" integer NOT NULL,
    "Lat" double precision DEFAULT 0 NOT NULL,
    "Lng" double precision DEFAULT 0 NOT NULL
);

CREATE TABLE "dbo"."SalaryProfiles" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "PersonType" varchar(10) NOT NULL,
    "PersonId" uuid NOT NULL,
    "BasicSalary" numeric(18,2) DEFAULT 0 NOT NULL,
    "Epf" numeric(18,2) DEFAULT 0 NOT NULL,
    "Uan" varchar(40),
    "BankHolder" varchar(120),
    "BankAccount" varchar(40),
    "BankName" varchar(120),
    "Ifsc" varchar(20),
    "BankBranch" varchar(120),
    "UpdatedAt" timestamptz DEFAULT now() NOT NULL,
    "Hra" numeric(18,2) DEFAULT 0 NOT NULL,
    "Allowances" numeric(18,2) DEFAULT 0 NOT NULL,
    "ProfTax" numeric(18,2) DEFAULT 0 NOT NULL,
    "OtherDeductions" numeric(18,2) DEFAULT 0 NOT NULL
);

CREATE TABLE "dbo"."SalaryStructures" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "PersonType" varchar(10) NOT NULL,
    "RoleKey" varchar(120) NOT NULL,
    "Basic" numeric(18,2) DEFAULT 0 NOT NULL,
    "Hra" numeric(18,2) DEFAULT 0 NOT NULL,
    "Allowances" numeric(18,2) DEFAULT 0 NOT NULL,
    "Epf" numeric(18,2) DEFAULT 0 NOT NULL,
    "ProfTax" numeric(18,2) DEFAULT 0 NOT NULL,
    "OtherDeductions" numeric(18,2) DEFAULT 0 NOT NULL,
    "UpdatedAt" timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE "dbo"."SchoolHouses" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "Name" varchar(80) NOT NULL
);

CREATE TABLE "dbo"."SchoolLocations" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "Lat" double precision DEFAULT 0 NOT NULL,
    "Lng" double precision DEFAULT 0 NOT NULL,
    "RadiusMeters" integer DEFAULT 50 NOT NULL,
    "Name" varchar(120)
);

CREATE TABLE "dbo"."Sibling" (
    "SiblingId" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    "StudentId" integer,
    "IsSameSchool" boolean,
    "SiblingName" varchar(100),
    "RollNo" integer,
    "AdmissionNo" varchar(50),
    "Class" varchar(50)
);

CREATE TABLE "dbo"."SportsEvents" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "Name" varchar(120) NOT NULL,
    "EventDate" date NOT NULL,
    "Venue" varchar(120)
);

CREATE TABLE "dbo"."SportsMedals" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "Kind" varchar(10) NOT NULL,
    "Title" varchar(120),
    "Year" integer NOT NULL
);

CREATE TABLE "dbo"."SportsTeams" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "Name" varchar(80) NOT NULL,
    "Sport" varchar(60) NOT NULL,
    "Coach" varchar(120),
    "Athletes" integer DEFAULT 0 NOT NULL
);

CREATE TABLE "dbo"."Staff" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "Name" varchar(200) NOT NULL,
    "Gender" varchar(1),
    "Role" varchar(80),
    "Category" varchar(40),
    "Department" varchar(80),
    "Phone" varchar(40),
    "Shift" varchar(40),
    "Route" varchar(80),
    "AttendancePct" numeric(5,2) DEFAULT 0 NOT NULL,
    "Status" varchar(20) DEFAULT 'active' NOT NULL,
    "AvatarHue" integer DEFAULT 0 NOT NULL,
    "CreatedAt" timestamptz DEFAULT now() NOT NULL,
    "EmployeeCode" varchar(64),
    "UserId" uuid,
    "Email" varchar(256)
);

CREATE TABLE "dbo"."StaffAttendanceRecords" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "PersonType" varchar(10) NOT NULL,
    "PersonId" uuid NOT NULL,
    "Date" date NOT NULL,
    "Status" varchar(20) NOT NULL,
    "MarkedBy" uuid
);

CREATE TABLE "dbo"."StaffDocuments" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "StaffId" uuid NOT NULL,
    "Label" varchar(120) NOT NULL,
    "Value" varchar(200) NOT NULL,
    "Ok" boolean,
    "CreatedAt" timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE "dbo"."StaffTasks" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "StaffId" uuid NOT NULL,
    "Title" varchar(200) NOT NULL,
    "Detail" varchar(1000),
    "Priority" varchar(10) DEFAULT 'normal' NOT NULL,
    "Done" boolean DEFAULT false NOT NULL,
    "DueLabel" varchar(60),
    "CreatedByUserId" uuid,
    "CreatedAt" timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE "dbo"."Student" (
    "StudentId" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    "OrganizationId" integer,
    "SchoolId" integer,
    "AcademicYear" varchar(50),
    "AdmissionNo" varchar(50),
    "AdmissionDate" date,
    "RollNo" integer,
    "Status" varchar(20),
    "FirstName" varchar(100),
    "LastName" varchar(100),
    "Gender" varchar(20),
    "DOB" date,
    "BloodGroup" varchar(10),
    "Religion" varchar(50),
    "Category" varchar(50),
    "Caste" varchar(50),
    "MotherTongue" varchar(50),
    "PrimaryContactNumber" varchar(20),
    "Email" varchar(100),
    "StudentPhoto" varchar(500),
    "Username" varchar(100),
    "PasswordHash" varchar(500),
    "CreatedBy" integer,
    "CreatedDate" timestamptz DEFAULT now(),
    "UpdatedBy" integer,
    "UpdatedDate" timestamptz,
    "IsActive" boolean DEFAULT true,
    "IsDeleted" boolean DEFAULT false
);

CREATE TABLE "dbo"."StudentBusAssignments" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "StudentId" uuid NOT NULL,
    "BusId" uuid,
    "StopId" uuid,
    "CreatedAt" timestamptz DEFAULT now() NOT NULL,
    "RouteId" uuid,
    "FeeHeadId" uuid
);

CREATE TABLE "dbo"."StudentDocument" (
    "DocumentId" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    "StudentId" integer,
    "MedicalDocument" varchar(500),
    "TransferCertificate" varchar(500)
);

CREATE TABLE "dbo"."StudentLanguage" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    "StudentId" integer,
    "Language" varchar(50)
);

CREATE TABLE "dbo"."Students" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "AdmissionNo" varchar(64) NOT NULL,
    "Name" varchar(200) NOT NULL,
    "Gender" varchar(1),
    "Grade" varchar(20),
    "Section" varchar(20),
    "ClassLabel" varchar(40),
    "Roll" integer DEFAULT 0 NOT NULL,
    "GuardianName" varchar(200),
    "GuardianPhone" varchar(40),
    "AttendancePct" numeric(5,2) DEFAULT 0 NOT NULL,
    "FeeStatus" varchar(20) DEFAULT 'due' NOT NULL,
    "FeeDue" numeric(18,2) DEFAULT 0 NOT NULL,
    "Status" varchar(20) DEFAULT 'active' NOT NULL,
    "House" varchar(40),
    "AvatarHue" integer DEFAULT 0 NOT NULL,
    "Dob" timestamptz,
    "Email" varchar(256),
    "Address" varchar(500),
    "CreatedAt" timestamptz DEFAULT now() NOT NULL,
    "PhotoUrl" text,
    "GuardianEmail" varchar(256)
);

CREATE TABLE "dbo"."StudentTransportOptOut" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "StudentId" uuid NOT NULL,
    "CreatedAt" timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE "dbo"."Subjects" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "Name" varchar(80) NOT NULL,
    "Short" varchar(20),
    "TeacherId" uuid,
    "Color" varchar(40),
    "AcademicSessionId" uuid
);

CREATE TABLE "dbo"."Subscriptions" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "PlanId" uuid NOT NULL,
    "Status" varchar(20) DEFAULT 'active' NOT NULL,
    "StartedAt" timestamptz DEFAULT now() NOT NULL,
    "RenewsAt" timestamptz,
    "Seats" integer DEFAULT 0 NOT NULL
);

CREATE TABLE "dbo"."Tasks" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "Title" varchar(200) NOT NULL,
    "Detail" varchar(2000),
    "Category" varchar(40),
    "AssignedToUserId" uuid,
    "AssignedToRoleKey" varchar(20),
    "Priority" varchar(10) DEFAULT 'normal' NOT NULL,
    "Status" varchar(20) DEFAULT 'pending' NOT NULL,
    "DueDate" date,
    "Remarks" varchar(2000),
    "PhotoUrl" text,
    "CreatedByUserId" uuid NOT NULL,
    "CompletedByUserId" uuid,
    "CreatedAt" timestamptz DEFAULT now() NOT NULL,
    "CompletedAt" timestamptz
);

CREATE TABLE "dbo"."Teachers" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "Name" varchar(200) NOT NULL,
    "Gender" varchar(1),
    "Department" varchar(80),
    "Designation" varchar(80),
    "SubjectsCsv" varchar(400),
    "ClassTeacher" varchar(40),
    "Phone" varchar(40),
    "Email" varchar(256),
    "Exp" integer DEFAULT 0 NOT NULL,
    "Rating" numeric(4,2) DEFAULT 0 NOT NULL,
    "AttendancePct" numeric(5,2) DEFAULT 0 NOT NULL,
    "Result" numeric(5,2) DEFAULT 0 NOT NULL,
    "Load" integer DEFAULT 0 NOT NULL,
    "Status" varchar(20) DEFAULT 'active' NOT NULL,
    "AvatarHue" integer DEFAULT 0 NOT NULL,
    "Top" boolean DEFAULT false NOT NULL,
    "CreatedAt" timestamptz DEFAULT now() NOT NULL,
    "EmployeeCode" varchar(64),
    "UserId" uuid
);

CREATE TABLE "dbo"."TeamDocuments" (
    "Id" uuid NOT NULL,
    "TeamMemberId" uuid NOT NULL,
    "Label" varchar(120) NOT NULL,
    "FileName" varchar(260) NOT NULL,
    "ContentType" varchar(120) NOT NULL,
    "SizeBytes" integer NOT NULL,
    "Content" text NOT NULL,
    "CreatedAt" timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE "dbo"."TeamMembers" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "Name" varchar(200) NOT NULL,
    "Email" varchar(256) NOT NULL,
    "Role" varchar(20) NOT NULL,
    "Status" varchar(20) DEFAULT 'invited' NOT NULL,
    "LastLogin" timestamptz,
    "Joined" timestamptz DEFAULT now() NOT NULL,
    "EmployeeId" varchar(40),
    "PhotoUrl" text,
    "Phone" varchar(40)
);

CREATE TABLE "dbo"."TenantPaymentCredentials" (
    "TenantId" uuid NOT NULL,
    "Provider" varchar(20) DEFAULT 'razorpay' NOT NULL,
    "KeyId" varchar(100),
    "KeySecretEncrypted" text,
    "WebhookSecretEncrypted" text,
    "Mode" varchar(10) DEFAULT 'test' NOT NULL,
    "IsEnabled" boolean DEFAULT false NOT NULL,
    "CreatedAt" timestamptz DEFAULT now() NOT NULL,
    "UpdatedAt" timestamptz
);

CREATE TABLE "dbo"."Tenants" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "Name" varchar(200) NOT NULL,
    "Slug" varchar(100) NOT NULL,
    "Status" varchar(20) DEFAULT 'trial' NOT NULL,
    "Tier" varchar(20),
    "CreatedAt" timestamptz DEFAULT now() NOT NULL,
    "Country" varchar(120),
    "PlanId" uuid,
    "PlanName" varchar(100),
    "Mrr" numeric(18,2) DEFAULT 0 NOT NULL,
    "StudentsCount" integer DEFAULT 0 NOT NULL,
    "StaffCount" integer DEFAULT 0 NOT NULL,
    "StorageGb" numeric(18,2) DEFAULT 0 NOT NULL,
    "LimitsStudents" integer,
    "LimitsStaff" integer,
    "LimitsStorageGb" integer,
    "ContactName" varchar(200),
    "ContactEmail" varchar(256),
    "ContactPhone" varchar(40),
    "Csm" varchar(120),
    "HealthScore" integer DEFAULT 100 NOT NULL,
    "Address" varchar(300),
    "LogoUrl" text,
    "ImageUrl" text,
    "Lat" double precision,
    "Lng" double precision,
    "GeofenceRadiusMeters" integer
);

CREATE TABLE "dbo"."TicketMessages" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TicketId" uuid NOT NULL,
    "Who" varchar(120),
    "Role" varchar(20) DEFAULT 'agent' NOT NULL,
    "Text" varchar(4000) NOT NULL,
    "When" timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE "dbo"."Tickets" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "Subject" varchar(300) NOT NULL,
    "TenantId" uuid,
    "TenantName" varchar(200),
    "Status" varchar(20) DEFAULT 'open' NOT NULL,
    "Priority" varchar(20) DEFAULT 'normal' NOT NULL,
    "Assignee" varchar(120),
    "Created" timestamptz DEFAULT now() NOT NULL,
    "Updated" timestamptz DEFAULT now() NOT NULL,
    "MessagesCount" integer DEFAULT 0 NOT NULL
);

CREATE TABLE "dbo"."TimetableSlots" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "Day" varchar(3) NOT NULL,
    "Period" integer NOT NULL,
    "Subject" varchar(80),
    "ClassId" uuid,
    "ClassName" varchar(80),
    "Room" varchar(40),
    "StartTime" varchar(10),
    "EndTime" varchar(10),
    "TeacherId" uuid,
    "AcademicSessionId" uuid
);

CREATE TABLE "dbo"."Transport" (
    "TransportId" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    "StudentId" integer,
    "RouteId" integer,
    "VehicleId" integer,
    "DriverId" integer,
    "PickupPoint" varchar(200)
);

CREATE TABLE "dbo"."TransportRoutes" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "Name" varchar(80) NOT NULL,
    "CreatedAt" timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE "dbo"."TripPings" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "TripId" uuid NOT NULL,
    "Lat" double precision DEFAULT 0 NOT NULL,
    "Lng" double precision DEFAULT 0 NOT NULL,
    "SpeedKmh" double precision DEFAULT 0 NOT NULL,
    "Heading" double precision DEFAULT 0 NOT NULL,
    "At" timestamptz NOT NULL,
    "Accuracy" double precision
);

CREATE TABLE "dbo"."Trips" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "RouteId" uuid,
    "BusNo" varchar(40),
    "DriverId" uuid,
    "ConductorId" uuid,
    "Direction" varchar(10) DEFAULT 'pickup' NOT NULL,
    "Status" varchar(10) DEFAULT 'live' NOT NULL,
    "StartedAt" timestamptz,
    "EndedAt" timestamptz,
    "BusId" uuid,
    "DriverLastPingAt" timestamptz,
    "ConductorLastPingAt" timestamptz,
    "CurrentStopId" uuid,
    "SchoolArrivedAt" timestamptz,
    "SchoolArrivedLat" double precision,
    "SchoolArrivedLng" double precision
);

CREATE TABLE "dbo"."TripStopProgress" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "TripId" uuid NOT NULL,
    "StopId" uuid NOT NULL,
    "Seq" integer NOT NULL,
    "ArrivedAt" timestamptz,
    "ConfirmedAt" timestamptz,
    "DepartedAt" timestamptz
);

CREATE TABLE "dbo"."UserAppSettings" (
    "UserId" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "ChatAlerts" boolean DEFAULT true NOT NULL,
    "SchoolNotices" boolean DEFAULT true NOT NULL,
    "InAppToasts" boolean DEFAULT true NOT NULL,
    "UpdatedAt" timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE "dbo"."UserLogin" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1001 INCREMENT BY 1),
    "UserId" integer,
    "EmailAddress" varchar(50),
    "PhoneNo" varchar(15),
    "Password" bytea,
    "OTP" varchar(20),
    "OTPVerify" boolean,
    "IsActive" boolean,
    "IsDelete" boolean,
    "CreatedBy" integer,
    "CreatedDateTime" timestamptz,
    "UpdatedBy" integer,
    "UpadtedDateTime" timestamptz
);

CREATE TABLE "dbo"."UserPermissions" (
    "UserId" uuid NOT NULL,
    "Module" varchar(64) NOT NULL,
    "Cap" char(1) NOT NULL,
    "Effect" varchar(16) NOT NULL
);

CREATE TABLE "dbo"."UserRoles" (
    "UserId" uuid NOT NULL,
    "Role" varchar(64) NOT NULL
);

CREATE TABLE "dbo"."Users" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid,
    "Email" varchar(256),
    "StudentId" varchar(64),
    "Phone" varchar(32),
    "PasswordHash" varchar(512),
    "IsPlatform" boolean DEFAULT false NOT NULL,
    "Status" varchar(20) DEFAULT 'active' NOT NULL,
    "CreatedAt" timestamptz DEFAULT now() NOT NULL,
    "Name" varchar(200),
    "MustSetPassword" boolean DEFAULT false NOT NULL,
    "LastSeenAt" timestamptz,
    "PhotoUrl" text
);

CREATE TABLE "dbo"."Vehicle" (
    "VehicleId" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    "OrganizationId" integer,
    "SchoolId" integer,
    "VehicleNumber" varchar(50),
    "VehicleType" varchar(50),
    "DriverId" integer
);

CREATE TABLE "dbo"."VehicleInspections" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TenantId" uuid NOT NULL,
    "BusId" uuid NOT NULL,
    "SubmittedByUserId" uuid NOT NULL,
    "Brakes" boolean NOT NULL,
    "Tyres" boolean NOT NULL,
    "Lights" boolean NOT NULL,
    "Horn" boolean NOT NULL,
    "FirstAidKit" boolean NOT NULL,
    "FireExtinguisher" boolean NOT NULL,
    "EmergencyExit" boolean NOT NULL,
    "FuelLevel" boolean NOT NULL,
    "AllOk" boolean NOT NULL,
    "Remarks" varchar(2000),
    "InspectionDate" date NOT NULL,
    "CreatedAt" timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE "dbo"."VersionInfo" (
    "Version" bigint NOT NULL,
    "AppliedOn" timestamptz,
    "Description" varchar(1024)
);
