-- Primary keys, unique constraints, check constraints, then foreign keys (dependency order: FKs last).

ALTER TABLE "dbo"."_Migration_UnmatchedDirectoryRows" ADD CONSTRAINT "PK___Migrati__3214EC07BDEEF373" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."AcademicPeriodSchedules" ADD CONSTRAINT "PK_AcademicPeriodSchedules" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."AcademicSessions" ADD CONSTRAINT "PK_AcademicSessions" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."Achievements" ADD CONSTRAINT "PK_Achievements" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."Address" ADD CONSTRAINT "PK__Address__091C2AFB3FE0DD71" PRIMARY KEY ("AddressId");
ALTER TABLE "dbo"."AiSearchConversation" ADD CONSTRAINT "PK_AiSearchConversation" PRIMARY KEY ("ConversationId");
ALTER TABLE "dbo"."AiSearchLog" ADD CONSTRAINT "PK_AiSearchLog" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."Announcements" ADD CONSTRAINT "PK_Announcements" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."Assignments" ADD CONSTRAINT "PK_Assignments" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."AttendanceAlertConfigs" ADD CONSTRAINT "PK_AttendanceAlertConfigs" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."AttendanceRecords" ADD CONSTRAINT "PK_AttendanceRecords" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."AuditLog" ADD CONSTRAINT "PK_AuditLog" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."AuditLogs" ADD CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."BankDetail" ADD CONSTRAINT "PK__BankDeta__AA08CB13C58C1B66" PRIMARY KEY ("BankId");
ALTER TABLE "dbo"."Boardings" ADD CONSTRAINT "PK_Boardings" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."BulkImportBatches" ADD CONSTRAINT "PK__BulkImpo__3214EC077B27AA52" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."BusAssignments" ADD CONSTRAINT "PK_BusAssignments" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."BusDriverAssignments" ADD CONSTRAINT "PK_BusDriverAssignments" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."Buses" ADD CONSTRAINT "PK_Buses" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."BusParentAlerts" ADD CONSTRAINT "PK_BusParentAlerts" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."BusStops" ADD CONSTRAINT "PK_BusStops" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."BusTravelingTeachers" ADD CONSTRAINT "PK_BusTravelingTeachers" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."CalendarEvents" ADD CONSTRAINT "PK_CalendarEvents" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."ChatMessages" ADD CONSTRAINT "PK_ChatMessages" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."ChatThreads" ADD CONSTRAINT "PK_ChatThreads" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."CheckIns" ADD CONSTRAINT "PK_CheckIns" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."Classes" ADD CONSTRAINT "PK_Classes" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."ClassSubjects" ADD CONSTRAINT "PK_ClassSubjects" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."ClassTestSchedules" ADD CONSTRAINT "PK_ClassTestSchedules" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."Complaints" ADD CONSTRAINT "PK_Complaints" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."Driver" ADD CONSTRAINT "PK__Driver__F1B1CD04F912AB43" PRIMARY KEY ("DriverId");
ALTER TABLE "dbo"."ExamAttendanceRecords" ADD CONSTRAINT "PK_ExamAttendanceRecords" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."ExamClasses" ADD CONSTRAINT "PK_ExamClasses" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."ExamPapers" ADD CONSTRAINT "PK_ExamPapers" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."Exams" ADD CONSTRAINT "PK_Exams" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."FeeHeads" ADD CONSTRAINT "PK_FeeHeads" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."FeeInvoiceLines" ADD CONSTRAINT "PK_FeeInvoiceLines" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."FeeInvoices" ADD CONSTRAINT "PK_FeeInvoices" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."FeePaymentOrders" ADD CONSTRAINT "PK_FeePaymentOrders" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."FeePayments" ADD CONSTRAINT "PK_FeePayments" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."FeeStructures" ADD CONSTRAINT "PK_FeeStructures" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."FuelLogs" ADD CONSTRAINT "PK_FuelLogs" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."Grades" ADD CONSTRAINT "PK_Grades" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."Guardian" ADD CONSTRAINT "PK__Guardian__0A5E1A9B59A38B63" PRIMARY KEY ("GuardianId");
ALTER TABLE "dbo"."Homework" ADD CONSTRAINT "PK_Homework" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."HostelBlocks" ADD CONSTRAINT "PK_HostelBlocks" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."HostelResidents" ADD CONSTRAINT "PK_HostelResidents" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."HostelRooms" ADD CONSTRAINT "PK_HostelRooms" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."Invitations" ADD CONSTRAINT "PK_Invitations" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."Invoices" ADD CONSTRAINT "PK_Invoices" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."IssueNotes" ADD CONSTRAINT "PK_IssueNotes" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."Issues" ADD CONSTRAINT "PK_Issues" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."LeaveEntitlements" ADD CONSTRAINT "PK_LeaveEntitlements" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."LeaveRequests" ADD CONSTRAINT "PK_LeaveRequests" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."LibraryBooks" ADD CONSTRAINT "PK_LibraryBooks" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."MedicalInfo" ADD CONSTRAINT "PK__MedicalI__4DD4333D7724FE84" PRIMARY KEY ("MedicalId");
ALTER TABLE "dbo"."Notifications" ADD CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."OnboardingChecklist" ADD CONSTRAINT "PK_OnboardingChecklist" PRIMARY KEY ("OnboardingId", "Seq");
ALTER TABLE "dbo"."OnboardingItems" ADD CONSTRAINT "PK_OnboardingItems" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."Organization" ADD CONSTRAINT "PK__Organiza__CADB0B12640E342F" PRIMARY KEY ("OrganizationId");
ALTER TABLE "dbo"."Organizations" ADD CONSTRAINT "PK__Organiza__CADB0B1286F05E2E" PRIMARY KEY ("OrganizationId");
ALTER TABLE "dbo"."OtpCodes" ADD CONSTRAINT "PK_OtpCodes" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."Parent" ADD CONSTRAINT "PK__Parent__D339516FDA4EB6F4" PRIMARY KEY ("ParentId");
ALTER TABLE "dbo"."ParentStudentLinks" ADD CONSTRAINT "PK_ParentStudentLinks" PRIMARY KEY ("ParentUserId", "StudentId");
ALTER TABLE "dbo"."PayrollRunLines" ADD CONSTRAINT "PK_PayrollRunLines" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."PayrollRuns" ADD CONSTRAINT "PK_PayrollRuns" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."Payslips" ADD CONSTRAINT "PK_Payslips" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."PeriodAttendanceAudit" ADD CONSTRAINT "PK_PeriodAttendanceAudit" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."PeriodAttendanceRecords" ADD CONSTRAINT "PK_PeriodAttendanceRecords" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."PersonExtras" ADD CONSTRAINT "PK_PersonExtras" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."Plans" ADD CONSTRAINT "PK_Plans" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."PlanUpgradeRequests" ADD CONSTRAINT "PK_PlanUpgradeRequests" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."PlatformMetricsSnapshot" ADD CONSTRAINT "PK_PlatformMetricsSnapshot" PRIMARY KEY ("Month");
ALTER TABLE "dbo"."PreviousSchool" ADD CONSTRAINT "PK__Previous__3214EC072C10B6A5" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."RefreshTokens" ADD CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."RoleTemplateOverrides" ADD CONSTRAINT "PK_RoleTemplateOverrides" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."Route" ADD CONSTRAINT "PK__Route__80979B4D2A8EE91B" PRIMARY KEY ("RouteId");
ALTER TABLE "dbo"."RouteGeometries" ADD CONSTRAINT "PK_RouteGeometries" PRIMARY KEY ("RouteId");
ALTER TABLE "dbo"."RouteStops" ADD CONSTRAINT "PK_RouteStops" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."SalaryProfiles" ADD CONSTRAINT "PK_SalaryProfiles" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."SalaryStructures" ADD CONSTRAINT "PK_SalaryStructures" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."SchoolHouses" ADD CONSTRAINT "PK_SchoolHouses" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."SchoolLocations" ADD CONSTRAINT "PK_SchoolLocations" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."Sibling" ADD CONSTRAINT "PK__Sibling__C3BB85C749E07926" PRIMARY KEY ("SiblingId");
ALTER TABLE "dbo"."SportsEvents" ADD CONSTRAINT "PK_SportsEvents" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."SportsMedals" ADD CONSTRAINT "PK_SportsMedals" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."SportsTeams" ADD CONSTRAINT "PK_SportsTeams" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."Staff" ADD CONSTRAINT "PK_Staff" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."StaffAttendanceRecords" ADD CONSTRAINT "PK_StaffAttendanceRecords" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."StaffDocuments" ADD CONSTRAINT "PK_StaffDocuments" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."StaffTasks" ADD CONSTRAINT "PK_StaffTasks" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."Student" ADD CONSTRAINT "PK__Student__32C52B99DA6DEA23" PRIMARY KEY ("StudentId");
ALTER TABLE "dbo"."StudentBusAssignments" ADD CONSTRAINT "PK_StudentBusAssignments" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."StudentDocument" ADD CONSTRAINT "PK__StudentD__1ABEEF0F85B3C4B8" PRIMARY KEY ("DocumentId");
ALTER TABLE "dbo"."StudentLanguage" ADD CONSTRAINT "PK__StudentL__3214EC076EFC0892" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."Students" ADD CONSTRAINT "PK_Students" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."StudentTransportOptOut" ADD CONSTRAINT "PK_StudentTransportOptOut" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."Subjects" ADD CONSTRAINT "PK_Subjects" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."Subscriptions" ADD CONSTRAINT "PK_Subscriptions" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."Tasks" ADD CONSTRAINT "PK_Tasks" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."Teachers" ADD CONSTRAINT "PK_Teachers" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."TeamDocuments" ADD CONSTRAINT "PK_TeamDocuments" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."TeamMembers" ADD CONSTRAINT "PK_TeamMembers" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."TenantPaymentCredentials" ADD CONSTRAINT "PK_TenantPaymentCredentials" PRIMARY KEY ("TenantId");
ALTER TABLE "dbo"."Tenants" ADD CONSTRAINT "PK_Tenants" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."TicketMessages" ADD CONSTRAINT "PK_TicketMessages" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."Tickets" ADD CONSTRAINT "PK_Tickets" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."TimetableSlots" ADD CONSTRAINT "PK_TimetableSlots" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."Transport" ADD CONSTRAINT "PK__Transpor__19E9A11D1A5926F0" PRIMARY KEY ("TransportId");
ALTER TABLE "dbo"."TransportRoutes" ADD CONSTRAINT "PK_TransportRoutes" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."TripPings" ADD CONSTRAINT "PK_TripPings" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."Trips" ADD CONSTRAINT "PK_Trips" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."TripStopProgress" ADD CONSTRAINT "PK_TripStopProgress" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."UserAppSettings" ADD CONSTRAINT "PK_UserAppSettings" PRIMARY KEY ("UserId");
ALTER TABLE "dbo"."UserLogin" ADD CONSTRAINT "PK__UserLogi__3214EC07801B6B81" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."UserPermissions" ADD CONSTRAINT "PK_UserPermissions" PRIMARY KEY ("UserId", "Module", "Cap");
ALTER TABLE "dbo"."UserRoles" ADD CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "Role");
ALTER TABLE "dbo"."Users" ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");
ALTER TABLE "dbo"."Vehicle" ADD CONSTRAINT "PK__Vehicle__476B54925F12F039" PRIMARY KEY ("VehicleId");
ALTER TABLE "dbo"."VehicleInspections" ADD CONSTRAINT "PK_VehicleInspections" PRIMARY KEY ("Id");

ALTER TABLE "dbo"."AcademicPeriodSchedules" ADD CONSTRAINT "UQ_AcademicPeriodSchedules_Tenant" UNIQUE ("TenantId");
ALTER TABLE "dbo"."AttendanceRecords" ADD CONSTRAINT "UQ_Attendance_Class_Student_Date" UNIQUE ("TenantId", "ClassId", "StudentId", "Date");
ALTER TABLE "dbo"."Boardings" ADD CONSTRAINT "UQ_Boardings_Trip_Student" UNIQUE ("TenantId", "TripId", "StudentId");
ALTER TABLE "dbo"."ClassSubjects" ADD CONSTRAINT "UQ_ClassSubjects_Class_Name" UNIQUE ("TenantId", "ClassId", "Name");
ALTER TABLE "dbo"."ClassTestSchedules" ADD CONSTRAINT "UQ_ClassTestSchedules_Tenant" UNIQUE ("TenantId");
ALTER TABLE "dbo"."ExamAttendanceRecords" ADD CONSTRAINT "UQ_ExamAttendance_Paper_Student" UNIQUE ("TenantId", "ExamPaperId", "StudentId");
ALTER TABLE "dbo"."ExamClasses" ADD CONSTRAINT "UQ_ExamClasses_Exam_Class" UNIQUE ("TenantId", "ExamId", "ClassId");
ALTER TABLE "dbo"."FeeHeads" ADD CONSTRAINT "UQ_FeeHeads_Tenant_Name" UNIQUE ("TenantId", "Name");
ALTER TABLE "dbo"."Grades" ADD CONSTRAINT "UQ_Grades_Paper_Student" UNIQUE ("TenantId", "ExamPaperId", "StudentId");
ALTER TABLE "dbo"."Organization" ADD CONSTRAINT "UQ__Organiza__536C85E44DF0261C" UNIQUE ("Username");
ALTER TABLE "dbo"."Organizations" ADD CONSTRAINT "UQ__Organiza__536C85E4AC813833" UNIQUE ("Username");
ALTER TABLE "dbo"."PeriodAttendanceRecords" ADD CONSTRAINT "UQ_PeriodAttendance_Class_Student_Date_Period_Subject" UNIQUE ("TenantId", "ClassId", "StudentId", "Date", "Period", "Subject");
ALTER TABLE "dbo"."PersonExtras" ADD CONSTRAINT "UQ_PersonExtras_Person" UNIQUE ("TenantId", "PersonType", "PersonId");
ALTER TABLE "dbo"."SchoolHouses" ADD CONSTRAINT "UQ_SchoolHouses_Tenant_Name" UNIQUE ("TenantId", "Name");
ALTER TABLE "dbo"."StaffAttendanceRecords" ADD CONSTRAINT "UQ_StaffAttendance_Type_Person_Date" UNIQUE ("TenantId", "PersonType", "PersonId", "Date");
ALTER TABLE "dbo"."Student" ADD CONSTRAINT "UQ__Student__536C85E43C10E4F5" UNIQUE ("Username");
ALTER TABLE "dbo"."StudentBusAssignments" ADD CONSTRAINT "UQ_StudentBus_Tenant_Student" UNIQUE ("TenantId", "StudentId");
ALTER TABLE "dbo"."StudentTransportOptOut" ADD CONSTRAINT "UQ_StudentTransportOptOut_Tenant_Student" UNIQUE ("TenantId", "StudentId");
ALTER TABLE "dbo"."TransportRoutes" ADD CONSTRAINT "UQ_TransportRoutes_Tenant_Name" UNIQUE ("TenantId", "Name");

ALTER TABLE "dbo"."UserPermissions" ADD CONSTRAINT "CK_UserPermissions_Cap" CHECK (("Cap"='A' OR "Cap"='E' OR "Cap"='V'));
ALTER TABLE "dbo"."UserPermissions" ADD CONSTRAINT "CK_UserPermissions_Effect" CHECK (("Effect"='revoke' OR "Effect"='grant'));
ALTER TABLE "dbo"."Tasks" ADD CONSTRAINT "CK_Tasks_ExactlyOneAssignmentTarget" CHECK (("AssignedToUserId" IS NOT NULL AND "AssignedToRoleKey" IS NULL OR "AssignedToUserId" IS NULL AND "AssignedToRoleKey" IS NOT NULL));

ALTER TABLE "dbo"."Address" ADD CONSTRAINT "FK__Address__Student__628FA481" FOREIGN KEY ("StudentId") REFERENCES "dbo"."Student" ("StudentId") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "dbo"."BankDetail" ADD CONSTRAINT "FK__BankDetai__Stude__6383C8BA" FOREIGN KEY ("StudentId") REFERENCES "dbo"."Student" ("StudentId") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "dbo"."Guardian" ADD CONSTRAINT "FK__Guardian__Studen__6477ECF3" FOREIGN KEY ("StudentId") REFERENCES "dbo"."Student" ("StudentId") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "dbo"."Invitations" ADD CONSTRAINT "FK_Invitations_User" FOREIGN KEY ("UserId") REFERENCES "dbo"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "dbo"."MedicalInfo" ADD CONSTRAINT "FK__MedicalIn__Stude__656C112C" FOREIGN KEY ("StudentId") REFERENCES "dbo"."Student" ("StudentId") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "dbo"."Parent" ADD CONSTRAINT "FK__Parent__StudentI__66603565" FOREIGN KEY ("StudentId") REFERENCES "dbo"."Student" ("StudentId") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "dbo"."PreviousSchool" ADD CONSTRAINT "FK__PreviousS__Stude__6754599E" FOREIGN KEY ("StudentId") REFERENCES "dbo"."Student" ("StudentId") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "dbo"."Sibling" ADD CONSTRAINT "FK__Sibling__Student__68487DD7" FOREIGN KEY ("StudentId") REFERENCES "dbo"."Student" ("StudentId") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "dbo"."StudentDocument" ADD CONSTRAINT "FK__StudentDo__Stude__693CA210" FOREIGN KEY ("StudentId") REFERENCES "dbo"."Student" ("StudentId") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "dbo"."StudentLanguage" ADD CONSTRAINT "FK__StudentLa__Stude__6A30C649" FOREIGN KEY ("StudentId") REFERENCES "dbo"."Student" ("StudentId") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "dbo"."TeamDocuments" ADD CONSTRAINT "FK_TeamDocuments_Member" FOREIGN KEY ("TeamMemberId") REFERENCES "dbo"."TeamMembers" ("Id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "dbo"."Transport" ADD CONSTRAINT "FK__Transport__Drive__6E01572D" FOREIGN KEY ("DriverId") REFERENCES "dbo"."Driver" ("DriverId") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "dbo"."Transport" ADD CONSTRAINT "FK__Transport__Route__6C190EBB" FOREIGN KEY ("RouteId") REFERENCES "dbo"."Route" ("RouteId") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "dbo"."Transport" ADD CONSTRAINT "FK__Transport__Stude__6B24EA82" FOREIGN KEY ("StudentId") REFERENCES "dbo"."Student" ("StudentId") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "dbo"."Transport" ADD CONSTRAINT "FK__Transport__Vehic__6D0D32F4" FOREIGN KEY ("VehicleId") REFERENCES "dbo"."Vehicle" ("VehicleId") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "dbo"."UserPermissions" ADD CONSTRAINT "FK_UserPermissions_User" FOREIGN KEY ("UserId") REFERENCES "dbo"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "dbo"."Vehicle" ADD CONSTRAINT "FK__Vehicle__DriverI__6EF57B66" FOREIGN KEY ("DriverId") REFERENCES "dbo"."Driver" ("DriverId") ON DELETE NO ACTION ON UPDATE NO ACTION;