-- All non-PK/non-unique-constraint indexes. NONCLUSTERED -> plain btree. Filtered indexes -> PARTIAL INDEX.
-- INCLUDE columns preserved via Postgres INCLUDE clause (PG 11+).

CREATE INDEX "IX_AcademicSessions_Tenant" ON "dbo"."AcademicSessions" ("TenantId", "IsCurrent");
CREATE INDEX "IX_Achievements_Tenant_Student" ON "dbo"."Achievements" ("TenantId", "StudentId", "AwardedOn" DESC);
CREATE INDEX "IX_AiSearchConversation_Expiry" ON "dbo"."AiSearchConversation" ("ExpiresAt");
CREATE INDEX "IX_AiSearchLog_Tenant_At" ON "dbo"."AiSearchLog" ("TenantId", "At" DESC);
CREATE INDEX "IX_Announcements_Tenant" ON "dbo"."Announcements" ("TenantId");
CREATE INDEX "IX_Assignments_Tenant" ON "dbo"."Assignments" ("TenantId");
CREATE UNIQUE INDEX "UX_AttendanceAlertConfigs_Tenant" ON "dbo"."AttendanceAlertConfigs" ("TenantId");
CREATE INDEX "IX_AuditLogs_Tenant_Entity" ON "dbo"."AuditLogs" ("TenantId", "EntityType", "EntityId");
CREATE UNIQUE INDEX "UX_BulkImportBatches_Tenant_Import_Batch" ON "dbo"."BulkImportBatches" ("TenantId", "ImportId", "BatchIndex");
CREATE UNIQUE INDEX "IX_BusAssignments_Teacher" ON "dbo"."BusAssignments" ("TenantId", "TeacherUserId");
CREATE INDEX "IX_BusDriverAssignments_Bus_AssignedAt" ON "dbo"."BusDriverAssignments" ("BusId", "AssignedAt" DESC);
CREATE INDEX "IX_BusDriverAssignments_Staff_AssignedAt" ON "dbo"."BusDriverAssignments" ("StaffId", "AssignedAt" DESC);
CREATE INDEX "IX_Buses_Tenant" ON "dbo"."Buses" ("TenantId");
CREATE UNIQUE INDEX "UX_BusParentAlerts_Trip_Student_Kind" ON "dbo"."BusParentAlerts" ("TripId", "StudentId", "Kind");
CREATE INDEX "IX_BusStops_Bus" ON "dbo"."BusStops" ("BusId");
CREATE UNIQUE INDEX "IX_BusTravelingTeachers_Bus_Teacher" ON "dbo"."BusTravelingTeachers" ("TenantId", "BusId", "TeacherUserId");
CREATE INDEX "IX_BusTravelingTeachers_Teacher" ON "dbo"."BusTravelingTeachers" ("TeacherUserId");
CREATE INDEX "IX_CalendarEvents_Tenant" ON "dbo"."CalendarEvents" ("TenantId");
CREATE INDEX "IX_ChatMessages_Correlation" ON "dbo"."ChatMessages" ("CorrelationId");
CREATE INDEX "IX_ChatMessages_Thread" ON "dbo"."ChatMessages" ("ThreadId");
CREATE INDEX "IX_ChatThreads_Contact" ON "dbo"."ChatThreads" ("TenantId", "OwnerUserId", "ContactUserId");
CREATE INDEX "IX_ChatThreads_Owner" ON "dbo"."ChatThreads" ("TenantId", "OwnerUserId", "Name");
CREATE INDEX "IX_ChatThreads_Tenant" ON "dbo"."ChatThreads" ("TenantId");
CREATE INDEX "IX_CheckIns_User_At" ON "dbo"."CheckIns" ("UserId", "At");
CREATE INDEX "IX_Classes_Tenant" ON "dbo"."Classes" ("TenantId");
CREATE INDEX "IX_ClassSubjects_Class" ON "dbo"."ClassSubjects" ("ClassId");
CREATE INDEX "IX_Complaints_Tenant" ON "dbo"."Complaints" ("TenantId");
CREATE INDEX "IX_ExamClasses_Exam" ON "dbo"."ExamClasses" ("ExamId");
CREATE INDEX "IX_ExamPapers_Tenant_Exam" ON "dbo"."ExamPapers" ("TenantId", "ExamId");
CREATE INDEX "IX_Exams_Tenant" ON "dbo"."Exams" ("TenantId");
CREATE INDEX "IX_FeeHeads_Tenant" ON "dbo"."FeeHeads" ("TenantId");
CREATE INDEX "IX_FeeInvoiceLines_Tenant_Invoice" ON "dbo"."FeeInvoiceLines" ("TenantId", "InvoiceId");
CREATE INDEX "IX_FeeInvoices_Tenant_Student" ON "dbo"."FeeInvoices" ("TenantId", "StudentId");
CREATE INDEX "IX_FeePaymentOrders_Tenant_Invoice" ON "dbo"."FeePaymentOrders" ("TenantId", "InvoiceId");
CREATE UNIQUE INDEX "UX_FeePaymentOrders_RazorpayOrderId" ON "dbo"."FeePaymentOrders" ("RazorpayOrderId");
CREATE INDEX "IX_FeePayments_Invoice" ON "dbo"."FeePayments" ("TenantId", "InvoiceId") WHERE ("InvoiceId" IS NOT NULL);
CREATE INDEX "IX_FeePayments_Tenant_Student" ON "dbo"."FeePayments" ("TenantId", "StudentId");
CREATE UNIQUE INDEX "UX_FeePayments_Tenant_IdempotencyKey" ON "dbo"."FeePayments" ("TenantId", "IdempotencyKey") WHERE ("IdempotencyKey" IS NOT NULL);
CREATE INDEX "IX_FeeStructures_Tenant" ON "dbo"."FeeStructures" ("TenantId");
CREATE INDEX "IX_FeeStructures_Tenant_CreatedAt" ON "dbo"."FeeStructures" ("TenantId", "CreatedAt" DESC);
CREATE INDEX "IX_FuelLogs_Bus_RecordedAt" ON "dbo"."FuelLogs" ("BusId", "RecordedAt" DESC);
CREATE INDEX "IX_FuelLogs_Tenant" ON "dbo"."FuelLogs" ("TenantId");
CREATE INDEX "IX_Homework_Tenant_Student" ON "dbo"."Homework" ("TenantId", "StudentId");
CREATE INDEX "IX_HostelBlocks_Tenant" ON "dbo"."HostelBlocks" ("TenantId");
CREATE INDEX "IX_HostelResidents_Room" ON "dbo"."HostelResidents" ("RoomId");
CREATE INDEX "IX_HostelRooms_Block" ON "dbo"."HostelRooms" ("BlockId");
CREATE INDEX "IX_Invitations_Tenant" ON "dbo"."Invitations" ("TenantId");
CREATE INDEX "IX_Invitations_UserId" ON "dbo"."Invitations" ("UserId");
CREATE INDEX "IX_Invoices_Tenant" ON "dbo"."Invoices" ("TenantId");
CREATE INDEX "IX_IssueNotes_Issue" ON "dbo"."IssueNotes" ("IssueId");
CREATE INDEX "IX_Issues_CreatedAt" ON "dbo"."Issues" ("CreatedAt" DESC);
CREATE INDEX "IX_Issues_Reporter" ON "dbo"."Issues" ("ReporterUserId");
CREATE INDEX "IX_Issues_Status" ON "dbo"."Issues" ("Status");
CREATE INDEX "IX_Issues_Tenant" ON "dbo"."Issues" ("TenantId");
CREATE UNIQUE INDEX "UX_LeaveEntitlements_Requester_Type_Year" ON "dbo"."LeaveEntitlements" ("TenantId", "RequesterId", "Type", "Year");
CREATE INDEX "IX_LeaveRequests_Tenant_Status" ON "dbo"."LeaveRequests" ("TenantId", "Status");
CREATE INDEX "IX_LibraryBooks_Tenant" ON "dbo"."LibraryBooks" ("TenantId");
CREATE INDEX "IX_Notifications_Tenant" ON "dbo"."Notifications" ("TenantId");
CREATE INDEX "IX_OtpCodes_Identifier" ON "dbo"."OtpCodes" ("Identifier");
CREATE INDEX "IX_ParentStudentLinks_Tenant_Student" ON "dbo"."ParentStudentLinks" ("TenantId", "StudentId");
CREATE INDEX "IX_PayrollRunLines_Run" ON "dbo"."PayrollRunLines" ("TenantId", "RunId");
CREATE UNIQUE INDEX "UX_PayrollRuns_Period" ON "dbo"."PayrollRuns" ("TenantId", "Period");
CREATE INDEX "IX_Payslips_Tenant_User" ON "dbo"."Payslips" ("TenantId", "UserId");
CREATE INDEX "IX_PeriodAttendanceAudit_Record" ON "dbo"."PeriodAttendanceAudit" ("TenantId", "RecordId", "At");
CREATE INDEX "IX_PeriodAttendance_Student_Date" ON "dbo"."PeriodAttendanceRecords" ("TenantId", "StudentId", "Date");
CREATE INDEX "IX_PeriodAttendance_Tenant_Class_Date" ON "dbo"."PeriodAttendanceRecords" ("TenantId", "ClassId", "Date");
CREATE INDEX "IX_PeriodAttendance_Tenant_Date" ON "dbo"."PeriodAttendanceRecords" ("TenantId", "Date");
CREATE INDEX "IX_PeriodAttendance_Tenant_MarkedBy" ON "dbo"."PeriodAttendanceRecords" ("TenantId", "MarkedBy");
CREATE INDEX "IX_PeriodAttendance_Tenant_Subject" ON "dbo"."PeriodAttendanceRecords" ("TenantId", "Subject");
CREATE INDEX "IX_PlanUpgradeRequests_RazorpayOrder" ON "dbo"."PlanUpgradeRequests" ("RazorpayOrderId");
CREATE INDEX "IX_PlanUpgradeRequests_Status" ON "dbo"."PlanUpgradeRequests" ("Status", "CreatedAt" DESC);
CREATE INDEX "IX_PlanUpgradeRequests_Tenant" ON "dbo"."PlanUpgradeRequests" ("TenantId", "CreatedAt" DESC);
CREATE INDEX "IX_RefreshTokens_Hash" ON "dbo"."RefreshTokens" ("TokenHash");
CREATE INDEX "IX_RoleTemplateOverrides_Tenant" ON "dbo"."RoleTemplateOverrides" ("TenantId");
CREATE UNIQUE INDEX "UX_RoleTemplateOverrides_Cell" ON "dbo"."RoleTemplateOverrides" ("TenantId", "Role", "Module", "Cap");
CREATE INDEX "IX_RouteStops_Route_Seq" ON "dbo"."RouteStops" ("RouteId", "Seq");
CREATE UNIQUE INDEX "UX_SalaryProfiles_Person" ON "dbo"."SalaryProfiles" ("TenantId", "PersonType", "PersonId");
CREATE UNIQUE INDEX "UX_SalaryStructures_Role" ON "dbo"."SalaryStructures" ("TenantId", "PersonType", "RoleKey");
CREATE INDEX "IX_SchoolHouses_Tenant" ON "dbo"."SchoolHouses" ("TenantId");
CREATE UNIQUE INDEX "IX_SchoolLocations_TenantId" ON "dbo"."SchoolLocations" ("TenantId");
CREATE INDEX "IX_SportsEvents_Tenant" ON "dbo"."SportsEvents" ("TenantId");
CREATE INDEX "IX_SportsMedals_Tenant" ON "dbo"."SportsMedals" ("TenantId");
CREATE INDEX "IX_SportsTeams_Tenant" ON "dbo"."SportsTeams" ("TenantId");
CREATE INDEX "IX_Staff_Tenant" ON "dbo"."Staff" ("TenantId");
CREATE UNIQUE INDEX "IX_Staff_UserId" ON "dbo"."Staff" ("UserId") WHERE ("UserId" IS NOT NULL);
CREATE UNIQUE INDEX "UX_Staff_Tenant_EmployeeCode" ON "dbo"."Staff" ("TenantId", "EmployeeCode") WHERE ("EmployeeCode" IS NOT NULL);
CREATE INDEX "IX_StaffDocuments_Staff_CreatedAt" ON "dbo"."StaffDocuments" ("StaffId", "CreatedAt");
CREATE INDEX "IX_StaffTasks_Staff_CreatedAt" ON "dbo"."StaffTasks" ("StaffId", "CreatedAt" DESC);
CREATE INDEX "IX_StudentBus_Tenant_Bus" ON "dbo"."StudentBusAssignments" ("TenantId", "BusId");
CREATE INDEX "IX_Students_Tenant_Class" ON "dbo"."Students" ("TenantId", "Grade", "Section");
CREATE UNIQUE INDEX "UX_Students_Tenant_AdmissionNo" ON "dbo"."Students" ("TenantId", "AdmissionNo");
CREATE INDEX "IX_Subjects_Tenant" ON "dbo"."Subjects" ("TenantId");
CREATE INDEX "IX_Subscriptions_Tenant" ON "dbo"."Subscriptions" ("TenantId");
CREATE INDEX "IX_Tasks_Tenant" ON "dbo"."Tasks" ("TenantId");
CREATE INDEX "IX_Tasks_Tenant_AssignedToRoleKey" ON "dbo"."Tasks" ("TenantId", "AssignedToRoleKey");
CREATE INDEX "IX_Tasks_Tenant_AssignedToUserId" ON "dbo"."Tasks" ("TenantId", "AssignedToUserId");
CREATE INDEX "IX_Teachers_Tenant" ON "dbo"."Teachers" ("TenantId");
CREATE UNIQUE INDEX "IX_Teachers_UserId" ON "dbo"."Teachers" ("UserId") WHERE ("UserId" IS NOT NULL);
CREATE UNIQUE INDEX "UX_Teachers_Tenant_EmployeeCode" ON "dbo"."Teachers" ("TenantId", "EmployeeCode") WHERE ("EmployeeCode" IS NOT NULL);
CREATE INDEX "IX_TeamDocuments_Member" ON "dbo"."TeamDocuments" ("TeamMemberId");
CREATE UNIQUE INDEX "UX_TeamMembers_EmployeeId" ON "dbo"."TeamMembers" ("EmployeeId") WHERE ("EmployeeId" IS NOT NULL);
CREATE UNIQUE INDEX "IX_Tenants_Slug" ON "dbo"."Tenants" ("Slug");
CREATE INDEX "IX_TicketMessages_Ticket" ON "dbo"."TicketMessages" ("TicketId");
CREATE INDEX "IX_TimetableSlots_Tenant" ON "dbo"."TimetableSlots" ("TenantId");
CREATE UNIQUE INDEX "UX_TimetableSlots_Class_Day_Period" ON "dbo"."TimetableSlots" ("TenantId", "ClassId", "Day", "Period") WHERE ("ClassId" IS NOT NULL);
CREATE INDEX "IX_TripPings_Trip_At" ON "dbo"."TripPings" ("TripId", "At");
CREATE INDEX "IX_Trips_Driver_Status" ON "dbo"."Trips" ("DriverId", "Status");
CREATE INDEX "IX_Trips_Tenant_Bus_Status" ON "dbo"."Trips" ("TenantId", "BusId", "Status");
CREATE INDEX "IX_TripStopProgress_Trip_Seq" ON "dbo"."TripStopProgress" ("TripId", "Seq");
CREATE UNIQUE INDEX "IX_TripStopProgress_Trip_Stop" ON "dbo"."TripStopProgress" ("TripId", "StopId");
CREATE INDEX "IX_UserAppSettings_Tenant" ON "dbo"."UserAppSettings" ("TenantId");
CREATE INDEX "IX_Users_Tenant_Email" ON "dbo"."Users" ("TenantId", "Email");
CREATE INDEX "IX_Users_Tenant_Name" ON "dbo"."Users" ("TenantId", "Name");
CREATE UNIQUE INDEX "UX_Users_PlatformAdmin" ON "dbo"."Users" ("Email") WHERE ("IsPlatform" = true);
CREATE UNIQUE INDEX "UX_Users_Tenant_Email" ON "dbo"."Users" ("TenantId", "Email") WHERE ("Email" IS NOT NULL);
CREATE UNIQUE INDEX "UX_Users_Tenant_Phone" ON "dbo"."Users" ("TenantId", "Phone") WHERE ("Phone" IS NOT NULL);
CREATE INDEX "IX_VehicleInspections_Bus" ON "dbo"."VehicleInspections" ("BusId");
CREATE INDEX "IX_VehicleInspections_Tenant" ON "dbo"."VehicleInspections" ("TenantId");
CREATE UNIQUE INDEX "UX_VehicleInspections_Tenant_Bus_Date" ON "dbo"."VehicleInspections" ("TenantId", "BusId", "InspectionDate");
CREATE UNIQUE INDEX "UC_Version" ON "dbo"."VersionInfo" ("Version");